# Authors ../model3d.pptx — a single embedded 3D model (PowerPoint 2019+ `am3d:model3d`).
#
# The payload is assets/cube.glb, generated by make-cube-glb.mjs so the fixture input is
# license-clean by construction. Geometry is pinned at round point values that convert to
# whole EMU (120/90/240/180 pt -> 1524000/1143000/3048000/2286000) so the emitted `p:xfrm`
# can be asserted exactly.
#
# Read .agents/skills/powerpoint-fixture-authoring/SKILL.md first — teardown/reap discipline
# and the Resiliency precondition live there.
#
#   & test\read\fixtures\authoring\author-model3d.ps1

$ErrorActionPreference = 'Stop'

$here = $PSScriptRoot
$glb = Join-Path $here 'assets\cube.glb'
$out = (Resolve-Path (Join-Path $here '..')).Path + '\model3d.pptx'
if (-not (Test-Path $glb)) { throw "missing $glb — run: node test/read/fixtures/authoring/make-cube-glb.mjs" }
if (Test-Path $out) { Remove-Item $out -Force }

# Document Recovery state left by a force-killed POWERPNT makes the next launch modal, which
# surfaces as RPC_E_CALL_REJECTED on the first automation call. Clear it before every run.
foreach ($sub in 'DocumentRecovery', 'StartupItems') {
	$key = "HKCU:\Software\Microsoft\Office\16.0\PowerPoint\Resiliency\$sub"
	if (Test-Path $key) { Remove-Item $key -Recurse -Force -ErrorAction SilentlyContinue }
}

$preexistingIds = @(Get-Process POWERPNT -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Id)
$pp = $null
$pres = $null
try {
	$pp = New-Object -ComObject PowerPoint.Application
	$pp.DisplayAlerts = 1
	$pres = $pp.Presentations.Add(1)
	$slide = $pres.Slides.Add(1, 12) # ppLayoutBlank

	# Add3DModel(FileName, LinkToFile, SaveWithDocument, Left, Top, Width, Height).
	# LinkToFile msoFalse => embedded; SaveWithDocument must then be msoTrue.
	$shape = $slide.Shapes.Add3DModel($glb, 0, -1, 120, 90, 240, 180)
	$shape.Name = 'Cube3D'

	# Report the model's resolved state so the findings block records what PowerPoint chose
	# rather than what the caller asked for.
	Write-Output ('shape.Type          : {0}' -f $shape.Type)   # 30 = mso3DModel
	Write-Output ('shape L/T/W/H       : {0} {1} {2} {3}' -f $shape.Left, $shape.Top, $shape.Width, $shape.Height)
	$m3d = $shape.Model3D
	foreach ($prop in 'CameraPositionX', 'CameraPositionY', 'CameraPositionZ', 'CameraFieldOfView', 'CameraLatitude', 'CameraLongitude', 'CameraRotation', 'PresetCamera') {
		try { Write-Output ('Model3D.{0} = {1}' -f $prop, $m3d.$prop) } catch { Write-Output ('Model3D.{0} = <no such property>' -f $prop) }
	}

	$pres.SaveAs($out)
	$pres.Saved = $true
	$pres.Close()
	$pp.Quit()
}
finally {
	if ($null -ne $pres) { [void][Runtime.InteropServices.Marshal]::ReleaseComObject($pres) }
	if ($null -ne $pp) { [void][Runtime.InteropServices.Marshal]::ReleaseComObject($pp) }
	[GC]::Collect()
	[GC]::WaitForPendingFinalizers()
	Get-Process POWERPNT -ErrorAction SilentlyContinue |
		Where-Object { $preexistingIds -notcontains $_.Id } |
		Stop-Process -Force -ErrorAction SilentlyContinue
}

Write-Output ''
Write-Output ('wrote {0} ({1} bytes)' -f $out, (Get-Item $out).Length)
