/**
 * Read proxies for a SmartArt diagram (`dgm:dataModel`) hosted in a `p:graphicFrame`.
 *
 * SmartArt is a four-part construct, and the frame itself holds none of it: the
 * `a:graphicData` carries only a `dgm:relIds` with four relationship ids pointing at the
 * data, layout, quick-style and colours parts under `/ppt/diagrams/`. The **data** part is
 * the one with content in it — a flat `dgm:ptLst` of points plus a `dgm:cxnLst` of
 * connections that give the points their tree — and it is what this surface decodes. The
 * other three are generated presets (`urn:microsoft.com/office/officeart/…`) describing how
 * PowerPoint *draws* the graph rather than what it says; they surface as parts, not getters.
 *
 * The text is ordinary DrawingML: `dgm:pt/dgm:t` is an `a:CT_TextBody`, the same type a
 * shape's `p:txBody` is, so a point's text reads back through the same
 * {@link TextFrame}/`Paragraph`/`Run` proxies as any other text on the slide, run formatting
 * included.
 *
 * **Not every point is content.** A saved data model interleaves the user's nodes with
 * points the layout engine generated (`pres`), the diagram root (`doc`), and the transition
 * points sitting on each edge (`parTrans`/`sibTrans`, which carry text only where a layout
 * labels its arrows). {@link Diagram.text} applies exactly that filter; {@link Diagram.points}
 * applies none, so a consumer that needs the raw graph gets it.
 *
 * Authoring SmartArt is out of scope: there is no write-side counterpart, and PowerPoint
 * regenerates the drawing from the data model, so a deck read here and saved back keeps its
 * diagram by preserving the parts rather than by re-authoring them.
 */
import type { OpcPackage } from '../opc/package.js'
import type { Part } from '../opc/part.js'
import type { Relationships } from '../opc/relationships.js'
import { attr, boolValue, firstChild, firstChildElement, getElements, intValue, type Element } from '../oxml/dom.js'
import type { ThemeContext } from '../oxml/theme.js'
import { TextFrame } from './text.js'

/**
 * `ST_PtType` — what a `dgm:pt` is.
 *
 * - `node` — a user-authored node, and the default when `@type` is absent.
 * - `asst` — an assistant node (an org chart's off-branch box); user content too.
 * - `doc` — the data model's single root; carries the layout/style/colour preset ids.
 * - `pres` — generated by the layout engine to position a node; never user content.
 * - `parTrans` / `sibTrans` — the two transition points of an edge, which a few layouts
 *   (arrow processes, org-chart branches) let the user type a label into.
 */
export type DiagramPointType = 'node' | 'asst' | 'doc' | 'pres' | 'parTrans' | 'sibTrans'

const POINT_TYPES: readonly string[] = ['node', 'asst', 'doc', 'pres', 'parTrans', 'sibTrans']

/**
 * `ST_CxnType` — what a `dgm:cxn` asserts. `parOf` (the default) is the parent/child edge of
 * the user's tree; `presOf` and `presParOf` bind a node to the generated `pres` point that
 * draws it, and are the layout engine's bookkeeping rather than structure.
 */
export type DiagramConnectionType = 'parOf' | 'presOf' | 'presParOf' | 'unknownRelationship'

const CONNECTION_TYPES: readonly string[] = ['parOf', 'presOf', 'presParOf', 'unknownRelationship']

/** The MS extension (`dgm:extLst/a:ext`) whose `@relId` names the fallback drawing part. */
const DRAWING_EXT_URI = 'http://schemas.microsoft.com/office/drawing/2008/diagram'

/**
 * One edge of a diagram's data model (`dgm:cxn`) — an attribute-only element, so it reads as
 * plain data rather than as a proxy.
 *
 * The ids are `ST_ModelId` GUIDs matching a {@link DiagramPoint.modelId}. `parOf` edges are
 * the tree a reader cares about: `sourceId` is the parent, `destinationId` the child, and
 * `sourceOrder` the child's position among its siblings.
 */
export interface DiagramConnection {
	/** This edge's own id (`@modelId`). */
	modelId: string | null
	/** What the edge asserts (`@type`); `parOf` when absent, its schema default. */
	type: DiagramConnectionType
	/** The `@srcId` end — the parent, for a `parOf` edge. */
	sourceId: string | null
	/** The `@destId` end — the child, for a `parOf` edge. */
	destinationId: string | null
	/** The child's index among its siblings (`@srcOrd`). */
	sourceOrder: number | null
	/** The parent's index as seen from the child (`@destOrd`). */
	destinationOrder: number | null
	/** The `parTrans` point labelling this edge (`@parTransId`), or `null` when unset. */
	parentTransitionId: string | null
	/** The `sibTrans` point labelling this edge (`@sibTransId`), or `null` when unset. */
	siblingTransitionId: string | null
	/** The layout preset this edge belongs to (`@presId`), set on generated edges only. */
	presentationId: string | null
}

/** One point (`dgm:pt`) of a diagram's data model. */
export class DiagramPoint {
	constructor(
		private readonly pt: Element,
		/** The diagram data part, so a text edit marks the right part dirty. */
		private readonly part: Part,
		private readonly themeContext?: ThemeContext,
		private readonly relationships?: Relationships
	) {}

	/** This point's id (`@modelId`), which connections reference. */
	get modelId(): string | null {
		return attr(this.pt, 'modelId')
	}

	/** What kind of point this is (`@type`); `node` when absent, its schema default. */
	get type(): DiagramPointType {
		const raw = attr(this.pt, 'type')
		return raw !== null && POINT_TYPES.includes(raw) ? (raw as DiagramPointType) : 'node'
	}

	/**
	 * For a transition point, the edge it labels (`@cxnId`), or `null`. The schema's default
	 * is the literal `0`, which means "none" rather than naming a point, so it reads `null`.
	 */
	get connectionId(): string | null {
		return idAttr(this.pt, 'cxnId')
	}

	/**
	 * Whether this point is an unfilled prompt (`dgm:prSet/@phldr`) — a node PowerPoint draws
	 * with a grey placeholder string and treats as empty. Excluded from {@link Diagram.text}:
	 * a layout that stores its prompt in `dgm:t` would otherwise extract as content.
	 */
	get isPlaceholder(): boolean {
		const prSet = this.#prSet()
		return prSet ? boolValue(attr(prSet, 'phldr')) === true : false
	}

	/** The prompt string a placeholder point displays (`dgm:prSet/@phldrT`), or `null`. */
	get placeholderText(): string | null {
		const prSet = this.#prSet()
		return prSet ? attr(prSet, 'phldrT') : null
	}

	/**
	 * This point's text body (`dgm:t`) as a {@link TextFrame}, or `null` when the point
	 * carries none. It is an `a:CT_TextBody` like any other, so `paragraphs`, `runs` and the
	 * `resolved*` getters all apply.
	 */
	get textFrame(): TextFrame | null {
		const t = firstChild(this.pt, 'dgm:t')
		return t ? new TextFrame(t, this.part, this.themeContext, undefined, this.relationships) : null
	}

	/** This point's text, paragraphs joined by `\n`; `''` when it carries none. */
	get text(): string {
		return this.textFrame?.text ?? ''
	}

	/** Escape hatch: the underlying `dgm:pt` element. After mutating it call {@link Diagram.markDirty}. */
	get element_(): Element {
		return this.pt
	}

	#prSet(): Element | null {
		return firstChild(this.pt, 'dgm:prSet')
	}
}

/** A SmartArt graphic frame's diagram, backed by its `dgm:dataModel` part. */
export class Diagram {
	constructor(
		/** The diagram's data part (`/ppt/diagrams/data{N}.xml`), whose root is `dgm:dataModel`. */
		readonly part: Part,
		/** The frame's `dgm:relIds`, which names the other three parts by relationship id. */
		private readonly relIds: Element,
		private readonly opc: OpcPackage,
		/** Relationships of the part holding the frame — what `dgm:relIds` resolves against. */
		private readonly frameRelationships: Relationships,
		private readonly themeContext?: ThemeContext
	) {}

	/** Partname of the diagram data part. */
	get partName(): string {
		return this.part.partName
	}

	/**
	 * Every point (`dgm:ptLst/dgm:pt`) in document order, unfiltered — generated `pres`
	 * points and the `doc` root included. Filter on {@link DiagramPoint.type} for the user's
	 * nodes; {@link text} is the shortcut for the common case.
	 */
	get points(): DiagramPoint[] {
		const root = this.#root()
		const ptLst = root && firstChild(root, 'dgm:ptLst')
		if (!ptLst) return []
		const relationships = this.opc.relationshipsFor(this.part.partName)
		return getElements(ptLst, 'dgm:pt').map((pt) => new DiagramPoint(pt, this.part, this.themeContext, relationships))
	}

	/** Every edge (`dgm:cxnLst/dgm:cxn`) in document order. */
	get connections(): DiagramConnection[] {
		const root = this.#root()
		const cxnLst = root && firstChild(root, 'dgm:cxnLst')
		if (!cxnLst) return []
		return getElements(cxnLst, 'dgm:cxn').map((cxn) => {
			const rawType = attr(cxn, 'type')
			return {
				modelId: attr(cxn, 'modelId'),
				type: rawType !== null && CONNECTION_TYPES.includes(rawType) ? (rawType as DiagramConnectionType) : 'parOf',
				sourceId: attr(cxn, 'srcId'),
				destinationId: attr(cxn, 'destId'),
				sourceOrder: intValue(attr(cxn, 'srcOrd')),
				destinationOrder: intValue(attr(cxn, 'destOrd')),
				parentTransitionId: idAttr(cxn, 'parTransId'),
				siblingTransitionId: idAttr(cxn, 'sibTransId'),
				presentationId: attr(cxn, 'presId') || null,
			}
		})
	}

	/**
	 * The diagram's text in document order, blocks joined by `\n` — the counterpart to
	 * `TextFrame.text` for a construct that has no single text body.
	 *
	 * Contributing points are the ones a user can type into: everything except the generated
	 * `pres` points, the `doc` root, and any point flagged as an unfilled placeholder. A
	 * point with no text contributes no blank line. Transition labels (`parTrans`/`sibTrans`)
	 * are included where a layout has them, which is why this is not simply the node list.
	 */
	get text(): string {
		return this.points
			.filter((point) => point.type !== 'pres' && point.type !== 'doc' && !point.isPlaceholder)
			.map((point) => point.text)
			.filter((text) => text.length > 0)
			.join('\n')
	}

	/**
	 * The layout preset the diagram is drawn with (the `doc` point's `dgm:prSet/@loTypeId`),
	 * e.g. `urn:microsoft.com/office/officeart/2005/8/layout/hList1`. This is what names the
	 * SmartArt *kind*; {@link layoutPart} is that preset's definition.
	 */
	get layoutTypeId(): string | null {
		return this.#docPrSetAttr('loTypeId')
	}

	/** The quick-style preset (the `doc` point's `dgm:prSet/@qsTypeId`). */
	get quickStyleTypeId(): string | null {
		return this.#docPrSetAttr('qsTypeId')
	}

	/** The colour preset (the `doc` point's `dgm:prSet/@csTypeId`). */
	get colorsTypeId(): string | null {
		return this.#docPrSetAttr('csTypeId')
	}

	/** The layout definition part (`dgm:relIds/@r:lo`), or `null` when missing from the package. */
	get layoutPart(): Part | null {
		return this.#relPart('r:lo')
	}

	/** The quick-style part (`dgm:relIds/@r:qs`), or `null` when missing from the package. */
	get quickStylePart(): Part | null {
		return this.#relPart('r:qs')
	}

	/** The colours part (`dgm:relIds/@r:cs`), or `null` when missing from the package. */
	get colorsPart(): Part | null {
		return this.#relPart('r:cs')
	}

	/**
	 * The fallback drawing part (`dsp:drawing`) that renders the diagram for a consumer with
	 * no SmartArt layout engine, or `null` when the deck carries none. It is named by an MS
	 * extension on the data model rather than by `dgm:relIds`, so a slide holding two
	 * diagrams still resolves each to its own drawing.
	 */
	get drawingPart(): Part | null {
		const root = this.#root()
		const extLst = root && firstChild(root, 'dgm:extLst')
		if (!extLst) return null
		for (const ext of getElements(extLst, 'a:ext')) {
			if (attr(ext, 'uri') !== DRAWING_EXT_URI) continue
			// Matched on local name alone: the `dsp` namespace appears nowhere else in the read
			// path, and registering a prefix for one attribute lookup buys nothing.
			const dataModelExt = firstChildElement(ext)
			if (!dataModelExt || dataModelExt.localName !== 'dataModelExt') continue
			return this.#partForRelId(attr(dataModelExt, 'relId'))
		}
		return null
	}

	/** Escape hatch: the underlying `dgm:dataModel` element. After mutating it call {@link markDirty}, or `save()` writes the original bytes. */
	get element_(): Element | null {
		return this.part.dom.documentElement
	}

	/** Mark the diagram data part dirty so `save()` reserializes it. Call after mutating {@link element_}. */
	markDirty(): void {
		this.part.markDirty()
	}

	#root(): Element | null {
		return this.part.dom.documentElement
	}

	#docPrSetAttr(name: string): string | null {
		const root = this.#root()
		const ptLst = root && firstChild(root, 'dgm:ptLst')
		if (!ptLst) return null
		const doc = getElements(ptLst, 'dgm:pt').find((pt) => attr(pt, 'type') === 'doc')
		const prSet = doc && firstChild(doc, 'dgm:prSet')
		return prSet ? attr(prSet, name) : null
	}

	#relPart(qname: string): Part | null {
		return this.#partForRelId(attr(this.relIds, qname))
	}

	#partForRelId(relId: string | null): Part | null {
		if (!relId) return null
		// A `dgm:relIds` id naming no relationship is a corrupt package rather than a missing
		// feature, so letting `resolveTarget` throw is the right outcome — the same contract
		// the chart and chartEx getters keep.
		return this.opc.part(this.frameRelationships.resolveTarget(relId)) ?? null
	}
}

/** An `ST_ModelId` attribute whose schema default `0` means "unset" rather than naming a point. */
function idAttr(element: Element, name: string): string | null {
	const raw = attr(element, name)
	return raw === null || raw === '' || raw === '0' ? null : raw
}
