/**
 * Read proxies for a SmartArt diagram (`dgm:dataModel`) hosted in a `p:graphicFrame`.
 *
 * SmartArt is a four-part construct, and the frame itself holds none of it: the
 * `a:graphicData` carries only a `dgm:relIds` with four relationship ids pointing at the
 * data, layout, quick-style and colours parts under `/ppt/diagrams/`. The **data** part is
 * the one with content in it — a flat `dgm:ptLst` of points plus a `dgm:cxnLst` of
 * connections that give the points their tree — and it is what this surface decodes. The
 * other three are generated presets (`urn:microsoft.com/office/officeart/…`) describing how
 * PowerPoint *draws* the graph rather than what it says; they surface as parts, not getters.
 *
 * The text is ordinary DrawingML: `dgm:pt/dgm:t` is an `a:CT_TextBody`, the same type a
 * shape's `p:txBody` is, so a point's text reads back through the same
 * {@link TextFrame}/`Paragraph`/`Run` proxies as any other text on the slide, run formatting
 * included.
 *
 * **Not every point is content.** A saved data model interleaves the user's nodes with
 * points the layout engine generated (`pres`), the diagram root (`doc`), and the transition
 * points sitting on each edge (`parTrans`/`sibTrans`, which carry text only where a layout
 * labels its arrows). {@link Diagram.text} applies exactly that filter; {@link Diagram.points}
 * applies none, so a consumer that needs the raw graph gets it.
 *
 * **The structure is in the connections, and {@link Diagram.nodes} is the view of it.** A
 * `parOf` edge names the parent in `@srcId`, the child in `@destId` and the child's sibling
 * position in `@srcOrd`; `points` order is document order and says nothing about depth. Three
 * decisions that tree makes, each of which could defensibly have gone the other way:
 *
 * - **`asst` points are in it.** An assistant is user content, and an org chart merely draws
 *   it off the main branch rather than under it. {@link DiagramPoint.type} carries the
 *   distinction, so folding it silently in with `node` would hide something a consumer can
 *   act on while omitting it would lose authored text.
 * - **Transition points are not.** A `parTrans`/`sibTrans` labels an *edge*, not a node, and
 *   reaches its edge through {@link DiagramConnection.parentTransitionId} /
 *   `siblingTransitionId`. Hanging one off `children` would make the tree disagree with what
 *   PowerPoint's own text pane shows.
 * - **A cycle in `parOf` throws.** It is a corrupt model rather than a shape the format can
 *   express, and the walk would not terminate; see `diagram/parent-edge-cycle`.
 *
 * **A point's text is stored twice.** The data model is what PowerPoint reads, but a deck
 * also carries a *drawing* part (`dsp:drawing`) holding a copy of every drawn string, and
 * every renderer without a SmartArt layout engine — LibreOffice, Google Slides, thumbnailers
 * — paints that copy and nothing else. {@link DiagramPoint.drawnShape} is the link between
 * the two, and {@link DiagramPoint.text}'s setter is what keeps them in step.
 *
 * Authoring a SmartArt graphic from nothing is out of scope: the layout part is a
 * constraint-solver program PowerPoint executes, and the presentation tree it generates is
 * not derivable from the user's content. Editing the text of one that already exists is
 * supported — see {@link DiagramPoint.text}.
 */
import { warn } from '../../diagnostics.js'
import { PackageReadError } from '../../errors.js'
import type { OpcPackage } from '../opc/package.js'
import type { Part } from '../opc/part.js'
import type { Relationships } from '../opc/relationships.js'
import {
	OOXML_NS,
	attr,
	boolValue,
	descendantsByTag,
	firstChild,
	firstChildElement,
	getElements,
	numberValue,
	type Element,
} from '../oxml/dom.js'
import type { ThemeContext } from '../oxml/theme.js'
import { setParagraphText, TextFrame } from './text.js'

/**
 * `ST_PtType` — what a `dgm:pt` is.
 *
 * - `node` — a user-authored node, and the default when `@type` is absent.
 * - `asst` — an assistant node (an org chart's off-branch box); user content too.
 * - `doc` — the data model's single root; carries the layout/style/colour preset ids.
 * - `pres` — generated by the layout engine to position a node; never user content.
 * - `parTrans` / `sibTrans` — the two transition points of an edge, which a few layouts
 *   (arrow processes, org-chart branches) let the user type a label into.
 */
export type DiagramPointType = 'node' | 'asst' | 'doc' | 'pres' | 'parTrans' | 'sibTrans'

const POINT_TYPES: readonly string[] = ['node', 'asst', 'doc', 'pres', 'parTrans', 'sibTrans']

/**
 * `ST_CxnType` — what a `dgm:cxn` asserts. `parOf` (the default) is the parent/child edge of
 * the user's tree; `presOf` and `presParOf` bind a node to the generated `pres` point that
 * draws it, and are the layout engine's bookkeeping rather than structure.
 */
export type DiagramConnectionType = 'parOf' | 'presOf' | 'presParOf' | 'unknownRelationship'

const CONNECTION_TYPES: readonly string[] = ['parOf', 'presOf', 'presParOf', 'unknownRelationship']

/** The MS extension (`dgm:extLst/a:ext`) whose `@relId` names the fallback drawing part. */
const DRAWING_EXT_URI = 'http://schemas.microsoft.com/office/drawing/2008/diagram'

/**
 * One edge of a diagram's data model (`dgm:cxn`) — an attribute-only element, so it reads as
 * plain data rather than as a proxy.
 *
 * The ids are `ST_ModelId` GUIDs matching a {@link DiagramPoint.modelId}. `parOf` edges are
 * the tree a reader cares about: `sourceId` is the parent, `destinationId` the child, and
 * `sourceOrder` the child's position among its siblings.
 */
export interface DiagramConnection {
	/** This edge's own id (`@modelId`). */
	modelId: string | null
	/** What the edge asserts (`@type`); `parOf` when absent, its schema default. */
	type: DiagramConnectionType
	/** The `@srcId` end — the parent, for a `parOf` edge. */
	sourceId: string | null
	/** The `@destId` end — the child, for a `parOf` edge. */
	destinationId: string | null
	/** The child's index among its siblings (`@srcOrd`). */
	sourceOrder: number | null
	/** The parent's index as seen from the child (`@destOrd`). */
	destinationOrder: number | null
	/** The `parTrans` point labelling this edge (`@parTransId`), or `null` when unset. */
	parentTransitionId: string | null
	/** The `sibTrans` point labelling this edge (`@sibTransId`), or `null` when unset. */
	siblingTransitionId: string | null
	/** The layout preset this edge belongs to (`@presId`), set on generated edges only. */
	presentationId: string | null
}

/**
 * Where a point's text is drawn in the fallback drawing part — the second copy of every
 * string a diagram carries, and the only one a renderer without a SmartArt layout engine
 * paints. See {@link DiagramPoint.drawnShape} for how a point reaches it.
 */
export interface DiagramDrawnShape {
	/** The drawing part (`/ppt/diagrams/drawing{N}.xml`) the shape lives in. */
	readonly part: Part
	/** The `pres` point this shape draws (`dsp:sp/@modelId`) — never the authored point's own id. */
	readonly modelId: string
	/** Which paragraph of {@link textFrame} carries this point's text (the `presOf` edge's `@destOrd`). */
	readonly paragraphIndex: number
	/**
	 * The shape's `dsp:txBody`, bound to the **drawing** part rather than the data part, so
	 * an edit made through it marks the part that actually changed.
	 *
	 * One shape commonly draws several points — three of them in `mixed.pptx` — so writing
	 * `textFrame.text` here would delete the siblings' text. Replace paragraph
	 * {@link paragraphIndex} instead, which is what {@link DiagramPoint.text}'s setter does.
	 */
	readonly textFrame: TextFrame
	/** Escape hatch: the underlying `dsp:sp`. After mutating it call `part.markDirty()`. */
	readonly element_: Element
}

/** One `presOf` edge out of a point, as the index keeps it. */
interface PresentationArm {
	readonly destId: string
	/** `@destOrd` — the paragraph index this point occupies inside the drawn shape. */
	readonly destinationOrder: number
	/** `@srcOrd` — which of the point's several presentations this is. */
	readonly sourceOrder: number
}

/**
 * The node → drawn-shape index of one diagram: the `presOf` edges of the data model and the
 * `dsp:sp` elements of the drawing part, both keyed for lookup.
 *
 * Built once per {@link Diagram}, and only when a point is actually asked what draws it — the
 * drawing part is a second XML DOM and a consumer reading node text should not pay to parse
 * it. The consequence of that memo: a consumer who *adds* or *removes* shapes in the drawing
 * part through the escape hatches must re-reach the diagram to see them here.
 */
class DrawingIndex {
	/** `presOf` arms out of each source point, in `@srcOrd` order. */
	readonly #arms = new Map<string, PresentationArm[]>()
	/** Each `dsp:sp` by the `pres` modelId it draws. */
	readonly #shapes = new Map<string, Element>()

	constructor(
		root: Element | null,
		private readonly drawingPart: Part | null,
		private readonly themeContext?: ThemeContext
	) {
		const cxnLst = root && firstChild(root, 'dgm:cxnLst')
		for (const cxn of cxnLst ? getElements(cxnLst, 'dgm:cxn') : []) {
			if (attr(cxn, 'type') !== 'presOf') continue
			const srcId = attr(cxn, 'srcId')
			const destId = attr(cxn, 'destId')
			if (!srcId || !destId) continue
			const arm: PresentationArm = {
				destId,
				destinationOrder: numberValue(attr(cxn, 'destOrd')) ?? 0,
				sourceOrder: numberValue(attr(cxn, 'srcOrd')) ?? 0,
			}
			const list = this.#arms.get(srcId)
			if (list) list.push(arm)
			else this.#arms.set(srcId, [arm])
		}
		for (const list of this.#arms.values()) list.sort((a, b) => a.sourceOrder - b.sourceOrder)

		// `dsp:spTree` nests, so this is a descendant scan rather than a child one. Matched on
		// the `dsp` namespace rather than on local name alone: `sp` and `txBody` are among the
		// most-reused local names in DrawingML, and unlike `dataModelExt` (which `drawingPart`
		// still matches loosely, because nothing else can appear in that extension) they carry
		// no uri to disambiguate them.
		const drawingRoot = drawingPart?.dom.documentElement ?? null
		for (const sp of drawingRoot ? descendantsByTag(drawingRoot, OOXML_NS.dsp, 'sp') : []) {
			const modelId = attr(sp, 'modelId')
			if (modelId !== null && !this.#shapes.has(modelId)) this.#shapes.set(modelId, sp)
		}
	}

	/**
	 * Resolve one authored point to the `pres` point that presents it and to the drawn
	 * paragraph carrying its text.
	 *
	 * A point commonly has **several** `presOf` arms — an org-chart node's box and the
	 * connector beneath it are two presentations of one node — so the arm is chosen by what it
	 * reaches rather than by its `@srcOrd`: the first, in `@srcOrd` order, whose `pres` point
	 * draws a `dsp:sp` that has a `dsp:txBody`. That selector produced a unique hit for all 90
	 * authored points measured across five layout families, and it degrades to "no arm" rather
	 * than to "the wrong arm" on a layout that was not.
	 */
	resolve(modelId: string | null): { presentationId: string | null; drawnShape: DiagramDrawnShape | null } {
		const arms = (modelId === null ? undefined : this.#arms.get(modelId)) ?? []
		const first = arms[0]
		if (!first) return { presentationId: null, drawnShape: null }
		for (const arm of arms) {
			const sp = this.#shapes.get(arm.destId)
			const txBody = sp && firstChild(sp, 'dsp:txBody')
			if (!sp || !txBody || !this.drawingPart) continue
			// A `@destOrd` past the end of the body is a drawing cache that disagrees with the
			// data model — no paragraph to point at, so the same "nothing is drawn" answer.
			const paragraph = getElements(txBody, 'a:p')[arm.destinationOrder]
			return {
				presentationId: arm.destId,
				drawnShape: paragraph
					? {
							part: this.drawingPart,
							modelId: arm.destId,
							paragraphIndex: arm.destinationOrder,
							textFrame: new TextFrame(txBody, this.drawingPart, this.themeContext),
							element_: sp,
						}
					: null,
			}
		}
		return { presentationId: first.destId, drawnShape: null }
	}
}

/** One point (`dgm:pt`) of a diagram's data model. */
export class DiagramPoint {
	constructor(
		private readonly pt: Element,
		/** The diagram data part, so a text edit marks the right part dirty. */
		private readonly part: Part,
		private readonly themeContext?: ThemeContext,
		private readonly relationships?: Relationships,
		/** The owning diagram's drawing index, built on first use; absent when reached without one. */
		private readonly drawing?: () => DrawingIndex
	) {}

	/** This point's id (`@modelId`), which connections reference. */
	get modelId(): string | null {
		return attr(this.pt, 'modelId')
	}

	/** What kind of point this is (`@type`); `node` when absent, its schema default. */
	get type(): DiagramPointType {
		const raw = attr(this.pt, 'type')
		return raw !== null && POINT_TYPES.includes(raw) ? (raw as DiagramPointType) : 'node'
	}

	/**
	 * For a transition point, the edge it labels (`@cxnId`), or `null`. The schema's default
	 * is the literal `0`, which means "none" rather than naming a point, so it reads `null`.
	 */
	get connectionId(): string | null {
		return idAttr(this.pt, 'cxnId')
	}

	/**
	 * Whether this point is an unfilled prompt (`dgm:prSet/@phldr`) — a node PowerPoint draws
	 * with a grey placeholder string and treats as empty. Excluded from {@link Diagram.text}:
	 * a layout that stores its prompt in `dgm:t` would otherwise extract as content.
	 */
	get isPlaceholder(): boolean {
		const prSet = this.#prSet()
		return prSet ? boolValue(attr(prSet, 'phldr')) === true : false
	}

	/** The prompt string a placeholder point displays (`dgm:prSet/@phldrT`), or `null`. */
	get placeholderText(): string | null {
		const prSet = this.#prSet()
		return prSet ? attr(prSet, 'phldrT') : null
	}

	/**
	 * This point's text body (`dgm:t`) as a {@link TextFrame}, or `null` when the point
	 * carries none. It is an `a:CT_TextBody` like any other, so `paragraphs`, `runs` and the
	 * `resolved*` getters all apply.
	 *
	 * **Writing through this edits the data model only**, and leaves the drawing cache
	 * holding the old string — which is what PowerPoint-less renderers draw. It is the escape
	 * hatch for run-level formatting, so it does exactly what it is told and nothing more;
	 * {@link text}'s setter is the path that mirrors.
	 */
	get textFrame(): TextFrame | null {
		const t = firstChild(this.pt, 'dgm:t')
		return t ? new TextFrame(t, this.part, this.themeContext, undefined, this.relationships) : null
	}

	/**
	 * The generated `pres` point that presents this one (`dgm:cxn[@type="presOf"]/@destId`),
	 * or `null` when nothing presents it — the normal state of an unlabelled transition point.
	 *
	 * Where a point has several `presOf` arms the one named here is the arm that draws text;
	 * see {@link drawnShape}, which resolves both.
	 */
	get presentationId(): string | null {
		return this.drawing?.().resolve(this.modelId).presentationId ?? null
	}

	/**
	 * The paragraph of the fallback drawing part (`dsp:drawing`) that carries this point's
	 * text, or `null` when nothing draws it.
	 *
	 * The mapping runs through the `pres` point rather than directly: a `dsp:sp/@modelId` is
	 * always a `pres` point's id, so a lookup keyed on the authored point's own id finds
	 * nothing at all. It is many-to-one in both directions — one shape draws several points
	 * (`@destOrd` says which paragraph is whose, and it can contradict document order), and
	 * one point has several presentations, of which at most one holds text.
	 *
	 * `null` is a defined outcome, not a failure, and covers four real cases: the package
	 * carries no drawing part; the point has no `presOf` edge (every unlabelled
	 * `parTrans`/`sibTrans`); the `pres` point draws no `dsp:sp`; and the shape it draws has
	 * no `dsp:txBody` (a connector, or a picture node's filled rectangle).
	 */
	get drawnShape(): DiagramDrawnShape | null {
		return this.drawing?.().resolve(this.modelId).drawnShape ?? null
	}

	/** This point's text, paragraphs joined by `\n`; `''` when it carries none. */
	get text(): string {
		return this.textFrame?.text ?? ''
	}

	/**
	 * Replace this point's text, in the data model **and** in the drawing cache.
	 *
	 * A diagram stores every string twice. `dgm:t` is what PowerPoint reads, and it recomputes
	 * the drawing from the data model on open; the `dsp:drawing` part is what every other
	 * renderer paints, and none of them recompute anything. Writing only the first is an edit
	 * that is invisible in LibreOffice, Google Slides, thumbnailers and web previews until
	 * someone opens the deck in PowerPoint and saves it.
	 *
	 * The data-model write always happens. The mirror is best-effort: when the point resolves
	 * to no drawn paragraph (see {@link drawnShape} for the four ways that occurs) the cache
	 * keeps the old string and a `diagram/drawing-cache-not-updated` diagnostic says so.
	 * Throwing instead would make the common case unusable in order to report the rare one,
	 * and returning a status would be a shape no other text setter here has.
	 *
	 * Two things it deliberately does not do. It does **not** recompute geometry: the drawn
	 * shape keeps its cached position and size, so a much longer string overflows its box in
	 * those same renderers until PowerPoint re-lays the diagram out. And it does not *create*
	 * a place to draw text — a transition point whose layout has no label slot has no
	 * `dsp:sp`, and PowerPoint strips text put on one, so the honest outcome is the
	 * diagnostic. Like every other `text` setter here it collapses the point to one run,
	 * keeping the first run's `a:rPr`; use {@link textFrame} for run-level work.
	 */
	set text(value: string) {
		const frame = this.textFrame
		if (!frame) {
			// No `dgm:t` at all. Synthesizing one is the case measurement says not to take: a
			// transition point whose layout has no label slot is stored exactly like this, and
			// PowerPoint strips text put on one at the next save. So the point is left alone.
			warn(
				'diagram/point-has-no-text-body',
				`SmartArt point ${this.#label()} (type ${this.type}) has no dgm:t, so it is not a point text can be written to; nothing was changed`
			)
			return
		}
		frame.text = value

		const drawn = this.drawnShape
		const paragraph = drawn?.textFrame.paragraphs[drawn.paragraphIndex]
		if (!drawn || !paragraph) {
			warn(
				'diagram/drawing-cache-not-updated',
				`SmartArt point ${this.#label()} resolves to no drawn paragraph, so ${this.part.partName} now holds the new text but the drawing cache still holds the old one; PowerPoint redraws it on open, other renderers do not`
			)
			return
		}
		setParagraphText(paragraph.element_, value)
		// The drawing is a different `Part` from the data model, and only a marked part is
		// reserialized — missing this one is silent, not loud.
		drawn.part.markDirty()
	}

	/** Escape hatch: the underlying `dgm:pt` element. After mutating it call {@link Diagram.markDirty}. */
	get element_(): Element {
		return this.pt
	}

	#prSet(): Element | null {
		return firstChild(this.pt, 'dgm:prSet')
	}

	/** How a diagnostic names this point: its `@modelId`, which is all a corrupt point may have. */
	#label(): string {
		return this.modelId ?? '(no modelId)'
	}
}

/**
 * One user-authored point in its place in the diagram's tree — a `node` or an `asst`, never a
 * generated `pres` point or a transition label. See {@link Diagram.nodes}.
 */
export class DiagramNode {
	/** Child nodes, ordered by their `parOf` edge's `@srcOrd`. Empty for a leaf. */
	readonly children: DiagramNode[] = []

	constructor(
		/** The point itself: its text, its type, and its link to what is drawn for it. */
		readonly point: DiagramPoint,
		/** The parent node, or `null` for a root. */
		readonly parent: DiagramNode | null,
		/** Depth below the root, `0` for a root. */
		readonly level: number
	) {}
}

/** A `parOf` edge, reduced to what building the tree needs. */
interface ParentEdge {
	readonly parentId: string
	readonly childId: string
	readonly order: number
}

/** Sort key for a root with no `parOf` edge at all, so it lands after the ordered ones. */
const MAX_ORDER = Number.MAX_SAFE_INTEGER

/** A SmartArt graphic frame's diagram, backed by its `dgm:dataModel` part. */
export class Diagram {
	#relationships: Relationships | undefined
	#docPrSetCache: Element | null | undefined
	#drawing: DrawingIndex | undefined

	constructor(
		/** The diagram's data part (`/ppt/diagrams/data{N}.xml`), whose root is `dgm:dataModel`. */
		readonly part: Part,
		/** The frame's `dgm:relIds`, which names the other three parts by relationship id. */
		private readonly relIds: Element,
		private readonly opc: OpcPackage,
		/** Relationships of the part holding the frame — what `dgm:relIds` resolves against. */
		private readonly frameRelationships: Relationships,
		private readonly themeContext?: ThemeContext
	) {}

	/** Partname of the diagram data part. */
	get partName(): string {
		return this.part.partName
	}

	/**
	 * Every point (`dgm:ptLst/dgm:pt`) in document order, unfiltered — generated `pres`
	 * points and the `doc` root included. Filter on {@link DiagramPoint.type} for the user's
	 * nodes; {@link text} is the shortcut for the common case, {@link nodes} the structured one.
	 *
	 * Built per access like every other read proxy (`docs/reference/pptx-read.md`, "Object
	 * model"), so `points[0] !== points[0]` while both wrap the same `dgm:pt`. Key a `Map`
	 * on {@link DiagramPoint.modelId}, not on the point.
	 */
	get points(): DiagramPoint[] {
		const root = this.#root()
		const ptLst = root && firstChild(root, 'dgm:ptLst')
		if (!ptLst) return []
		const relationships = (this.#relationships ??= this.opc.relationshipsFor(this.part.partName))
		const drawing = (): DrawingIndex => this.#drawingIndex()
		return getElements(ptLst, 'dgm:pt').map(
			(pt) => new DiagramPoint(pt, this.part, this.themeContext, relationships, drawing)
		)
	}

	/**
	 * The authored tree — every `node` and `asst` point in its place, roots in `@srcOrd`
	 * order — as a view over {@link points} and {@link connections} rather than a replacement
	 * for either.
	 *
	 * A root is a content point whose `parOf` parent is not itself content, which in a
	 * PowerPoint-authored model means the `doc` point. Transition points are not members; see
	 * this module's header for that decision and the two beside it.
	 *
	 * @throws PackageReadError `diagram/parent-edge-cycle` when the `parOf` edges make a
	 * point its own ancestor, which is a corrupt model rather than a diagram shape.
	 */
	get nodes(): DiagramNode[] {
		const content = new Map<string, DiagramPoint>()
		for (const point of this.points) {
			const modelId = point.modelId
			if (modelId !== null && (point.type === 'node' || point.type === 'asst')) content.set(modelId, point)
		}

		const childrenOf = new Map<string, ParentEdge[]>()
		const edgeTo = new Map<string, ParentEdge>()
		for (const connection of this.connections) {
			const { sourceId, destinationId } = connection
			if (connection.type !== 'parOf' || sourceId === null || destinationId === null) continue
			if (!content.has(destinationId)) continue
			const edge: ParentEdge = { parentId: sourceId, childId: destinationId, order: connection.sourceOrder ?? 0 }
			const list = childrenOf.get(sourceId)
			if (list) list.push(edge)
			else childrenOf.set(sourceId, [edge])
			edgeTo.set(destinationId, edge)
		}
		for (const list of childrenOf.values()) list.sort((a, b) => a.order - b.order)

		// `content` is in document order and `sort` is stable, so a point with no `parOf` edge
		// at all — a hand-built model, not something PowerPoint writes — keeps its place at the
		// end rather than being dropped.
		const roots = [...content].filter(([modelId]) => {
			const parentId = edgeTo.get(modelId)?.parentId
			return parentId === undefined || !content.has(parentId)
		})
		roots.sort(([a], [b]) => (edgeTo.get(a)?.order ?? MAX_ORDER) - (edgeTo.get(b)?.order ?? MAX_ORDER))

		const placed = new Set<string>()
		const build = (point: DiagramPoint, parent: DiagramNode | null, level: number, path: Set<string>): DiagramNode => {
			const modelId = point.modelId
			if (modelId !== null && path.has(modelId)) throw this.#cycleError(modelId)
			const node = new DiagramNode(point, parent, level)
			if (modelId === null) return node
			placed.add(modelId)
			path.add(modelId)
			for (const edge of childrenOf.get(modelId) ?? []) {
				const child = content.get(edge.childId)
				if (child) node.children.push(build(child, node, level + 1, path))
			}
			path.delete(modelId)
			return node
		}
		const tree = roots.map(([, point]) => build(point, null, 0, new Set()))

		// A cycle that no root reaches would otherwise drop its members from the tree in
		// silence, since the walk never enters it. Every content point has at most one recorded
		// parent, so following parents from an unplaced point must repeat: unreachable and
		// cyclic are the same condition, and it gets the same answer as the reachable form.
		if (placed.size !== content.size) {
			const orphan = [...content.keys()].find((modelId) => !placed.has(modelId))
			throw this.#cycleError(orphan ?? '(unidentified)')
		}
		return tree
	}

	/**
	 * The point with this `@modelId`, or `null` — the lookup every connection getter implies,
	 * since a `DiagramConnection` names its ends by id and nothing else resolves them.
	 */
	point(modelId: string): DiagramPoint | null {
		return this.points.find((candidate) => candidate.modelId === modelId) ?? null
	}

	/** Every edge (`dgm:cxnLst/dgm:cxn`) in document order. */
	get connections(): DiagramConnection[] {
		const root = this.#root()
		const cxnLst = root && firstChild(root, 'dgm:cxnLst')
		if (!cxnLst) return []
		return getElements(cxnLst, 'dgm:cxn').map((cxn) => {
			const rawType = attr(cxn, 'type')
			return {
				modelId: attr(cxn, 'modelId'),
				type: rawType !== null && CONNECTION_TYPES.includes(rawType) ? (rawType as DiagramConnectionType) : 'parOf',
				sourceId: attr(cxn, 'srcId'),
				destinationId: attr(cxn, 'destId'),
				sourceOrder: numberValue(attr(cxn, 'srcOrd')),
				destinationOrder: numberValue(attr(cxn, 'destOrd')),
				parentTransitionId: idAttr(cxn, 'parTransId'),
				siblingTransitionId: idAttr(cxn, 'sibTransId'),
				presentationId: attr(cxn, 'presId') || null,
			}
		})
	}

	/**
	 * The diagram's text in document order, blocks joined by `\n` — the counterpart to
	 * `TextFrame.text` for a construct that has no single text body.
	 *
	 * Contributing points are the ones a user can type into: everything except the generated
	 * `pres` points, the `doc` root, and any point flagged as an unfilled placeholder. A
	 * point with no text contributes no blank line. Transition labels (`parTrans`/`sibTrans`)
	 * are included where a layout has them, which is why this is not simply the node list.
	 */
	get text(): string {
		return this.points
			.filter((point) => point.type !== 'pres' && point.type !== 'doc' && !point.isPlaceholder)
			.map((point) => point.text)
			.filter((text) => text.length > 0)
			.join('\n')
	}

	/**
	 * The layout preset the diagram is drawn with (the `doc` point's `dgm:prSet/@loTypeId`),
	 * e.g. `urn:microsoft.com/office/officeart/2005/8/layout/hList1`. This is what names the
	 * SmartArt *kind*; {@link layoutPart} is that preset's definition.
	 */
	get layoutTypeId(): string | null {
		return this.#docPrSetAttr('loTypeId')
	}

	/** The quick-style preset (the `doc` point's `dgm:prSet/@qsTypeId`). */
	get quickStyleTypeId(): string | null {
		return this.#docPrSetAttr('qsTypeId')
	}

	/** The colour preset (the `doc` point's `dgm:prSet/@csTypeId`). */
	get colorsTypeId(): string | null {
		return this.#docPrSetAttr('csTypeId')
	}

	/** The layout definition part (`dgm:relIds/@r:lo`), or `null` when missing from the package. */
	get layoutPart(): Part | null {
		return this.#relPart('r:lo')
	}

	/** The quick-style part (`dgm:relIds/@r:qs`), or `null` when missing from the package. */
	get quickStylePart(): Part | null {
		return this.#relPart('r:qs')
	}

	/** The colours part (`dgm:relIds/@r:cs`), or `null` when missing from the package. */
	get colorsPart(): Part | null {
		return this.#relPart('r:cs')
	}

	/**
	 * The fallback drawing part (`dsp:drawing`) that renders the diagram for a consumer with
	 * no SmartArt layout engine, or `null` when the deck carries none. It is named by an MS
	 * extension on the data model rather than by `dgm:relIds`, so a slide holding two
	 * diagrams still resolves each to its own drawing.
	 */
	get drawingPart(): Part | null {
		const root = this.#root()
		const extLst = root && firstChild(root, 'dgm:extLst')
		if (!extLst) return null
		for (const ext of getElements(extLst, 'a:ext')) {
			if (attr(ext, 'uri') !== DRAWING_EXT_URI) continue
			// Matched on local name alone: the `dsp` namespace appears nowhere else in the read
			// path, and registering a prefix for one attribute lookup buys nothing.
			const dataModelExt = firstChildElement(ext)
			if (!dataModelExt || dataModelExt.localName !== 'dataModelExt') continue
			return this.#partForRelId(attr(dataModelExt, 'relId'))
		}
		return null
	}

	/** Escape hatch: the underlying `dgm:dataModel` element. After mutating it call {@link markDirty}, or `save()` writes the original bytes. */
	get element_(): Element | null {
		return this.part.dom.documentElement
	}

	/** Mark the diagram data part dirty so `save()` reserializes it. Call after mutating {@link element_}. */
	markDirty(): void {
		this.part.markDirty()
	}

	#root(): Element | null {
		return this.part.dom.documentElement
	}

	#cycleError(modelId: string): PackageReadError {
		return new PackageReadError(
			'diagram/parent-edge-cycle',
			`Diagram ${this.part.partName} has a parOf cycle reaching point ${modelId}, so its points do not form a tree`
		)
	}

	/**
	 * The `doc` point's `dgm:prSet`, which carries all three preset ids — resolved once
	 * rather than once per getter, since each lookup is a scan of the whole `ptLst`.
	 * `undefined` means "not looked up yet"; `null` means "looked up, not there".
	 */
	#docPrSet(): Element | null {
		if (this.#docPrSetCache !== undefined) return this.#docPrSetCache
		const root = this.#root()
		const ptLst = root && firstChild(root, 'dgm:ptLst')
		const doc = ptLst && getElements(ptLst, 'dgm:pt').find((pt) => attr(pt, 'type') === 'doc')
		return (this.#docPrSetCache = (doc && firstChild(doc, 'dgm:prSet')) || null)
	}

	#docPrSetAttr(name: string): string | null {
		const prSet = this.#docPrSet()
		return prSet ? attr(prSet, name) : null
	}

	/**
	 * The drawing index, built on first use and kept — see {@link DrawingIndex} for what that
	 * memo costs a consumer who mutates the drawing part's shape tree by hand.
	 */
	#drawingIndex(): DrawingIndex {
		return (this.#drawing ??= new DrawingIndex(this.#root(), this.drawingPart, this.themeContext))
	}

	#relPart(qname: string): Part | null {
		return this.#partForRelId(attr(this.relIds, qname))
	}

	#partForRelId(relId: string | null): Part | null {
		if (!relId) return null
		// A `dgm:relIds` id naming no relationship is a corrupt package rather than a missing
		// feature, so letting `resolveTarget` throw is the right outcome — the same contract
		// the chart and chartEx getters keep.
		return this.opc.part(this.frameRelationships.resolveTarget(relId)) ?? null
	}
}

/** An `ST_ModelId` attribute whose schema default `0` means "unset" rather than naming a point. */
function idAttr(element: Element, name: string): string | null {
	const raw = attr(element, name)
	return raw === null || raw === '' || raw === '0' ? null : raw
}
