#!/usr/bin/env node
// Scaffold the small-project documentation kit: the docs skill, docs.json navigation, and the
// four starter pages, plus the `docs:*` scripts in package.json.
//
// This is a bootstrap for a *fresh* repo. In this one it is effectively inert — every file it
// writes already exists, so a plain run reports `preserve:` for all of them — but it is kept so
// the kit stays reproducible and so the canonical script list has one home.
//
// Keep PACKAGE_SCRIPTS in step with package.json. It is not decorative: `addPackageScripts`
// rewrites any script whose command differs, so a stale entry here silently *downgrades* a real
// repo. That is not hypothetical — this file previously claimed `python3 scripts/docs-*.py` long
// after the scripts had moved behind a Node shim, so running `docs:init` would have broken the
// docs pipeline it exists to install.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { parseArgs } from 'node:util'

const PROJECT_NAME = 'ts-pptx'

const PACKAGE_SCRIPTS = {
	'docs:init': 'node scripts/docs-init.mjs',
	'docs:list': 'node scripts/docs-list.mjs',
	'docs:new': 'node scripts/docs-new.mjs',
	'docs:api': 'node scripts/docs-api.mjs',
	'docs:llms': 'node scripts/generate-llms-docs.mjs',
	'docs:index': 'node scripts/docs-index.mjs',
	'docs:check': 'pnpm run docs:api && node scripts/docs-check.mjs',
	'docs:prepare': 'pnpm run docs:api && pnpm run docs:llms && pnpm run docs:index',
	'docs:dev': 'pnpm run docs:prepare && vitepress dev docs',
	'docs:build': 'pnpm run docs:prepare && node scripts/docs-check.mjs && vitepress build docs',
	'docs:preview': 'vitepress preview docs',
}

const TEMPLATES = {
	'.agents/skills/project-documentation/SKILL.md': `---
name: project-documentation
description: Use when creating, updating, or reviewing README, docs, AGENTS.md, CLI docs, config docs, architecture docs, troubleshooting docs, or behavior-linked documentation in this repository.
---

# Project Documentation

Use this skill for documentation work in this repository.

## Workflow

1. Run \`pnpm run docs:list\` when available.
2. Read the docs whose \`read_when\` hints match the task.
3. Inspect source, tests, package scripts, CLI help, config schemas, and current
   docs before making behavior-sensitive claims.
4. Update docs when architecture, APIs, CLI commands, config, setup, or user
   workflows change.
5. Use \`pnpm run docs:new -- <slug> --title "..." --summary "..."\`
   for new pages.
6. Update \`docs/docs.json\` when a page should be discoverable in navigation.
7. Run \`pnpm run docs:check\` before handoff so generated API docs are refreshed
   before scaffold validation.

## Page Rules

Every page under \`docs/\` needs frontmatter:

\`\`\`yaml
---
doc-schema-version: 1
title: "Page Title"
summary: "One sentence describing this page."
read_when:
  - When an agent should read this page
doc_type: "guide"
---
\`\`\`

Allowed \`doc_type\` values: \`overview\`, \`architecture\`, \`guide\`, \`reference\`,
\`troubleshooting\`, \`decision\`, \`runbook\`.

## Source-Backed Claims

- CLI docs come from implementation, help output, package scripts, and tests.
- Config docs come from schemas, defaults, parser code, and generated metadata.
- API docs come from exported types, handlers, and tests.
- Architecture docs come from current module boundaries.
- Dependency behavior comes from upstream docs/source/types.

Separate current behavior, planned behavior, and TODOs. Do not invent behavior
to make a page feel complete.

## Generated Site Docs

- \`docs/docs.json\` is the canonical navigation source for agents and VitePress.
- \`docs/reference/api/\` is generated by \`pnpm run docs:api\` from public package
  entry points and should not be hand-edited.
- \`docs/public/llms.txt\` and \`docs/public/llms-full.txt\` are generated by
  \`pnpm run docs:llms\`.
- Run \`pnpm run docs:build\` to verify the generated TypeDoc reference,
  \`llms.txt\`, scaffold docs checks, and the VitePress static site together.
`,
	'docs/docs.json': `{
  "name": "ts-pptx",
  "description": "Documentation for ts-pptx.",
  "navigation": [
    {
      "group": "Start",
      "pages": ["index", "architecture"]
    },
    {
      "group": "Reference",
      "pages": ["reference/index", "troubleshooting"]
    }
  ]
}
`,
	'docs/index.md': `---
doc-schema-version: 1
title: "ts-pptx"
summary: "Start here for the purpose, setup, and main workflows in ts-pptx."
read_when:
  - Getting oriented in this project
  - Updating the main project overview
doc_type: "overview"
---

# ts-pptx

This page is the documentation entry point for ts-pptx.

## What This Project Does

Describe the job this project performs, who uses it, and what it intentionally
does not own.

## Quickstart

Add the shortest reliable path from a fresh checkout to a working result.

## Main Workflows

Link to setup, architecture, reference, and troubleshooting pages as they become
useful.

## Verification

Record the smallest command that proves the current project still works.
`,
	'docs/architecture.md': `---
doc-schema-version: 1
title: "Architecture"
summary: "How ts-pptx is structured and where major responsibilities live."
read_when:
  - Changing module boundaries
  - Explaining architecture or ownership decisions
  - Reviewing whether a new feature belongs in the current structure
doc_type: "architecture"
---

# Architecture

Use this page to keep the project's structure legible as features evolve.

## Responsibilities

Describe the main modules, packages, services, or scripts and what each owns.

## Boundaries

Call out decisions that should not be rediscovered during routine feature work.

## Data And Control Flow

Describe important runtime flows when they become stable enough to document.

## Extension Points

List supported ways to add behavior without rewriting core code.
`,
	'docs/reference/index.md': `---
doc-schema-version: 1
title: "Reference"
summary: "Stable commands, configuration, APIs, and generated references for ts-pptx."
read_when:
  - Looking up command, config, or API details
  - Adding a reference page
  - Verifying docs against exported contracts
doc_type: "reference"
---

# Reference

Keep exhaustive contracts here instead of burying them in guides.

## Commands

Document stable commands, flags, inputs, outputs, and exit codes.

## Configuration

Document supported config fields, defaults, precedence, and migration notes.

## APIs

Document stable public APIs, request/response shapes, errors, and lifecycle
states.
`,
	'docs/troubleshooting.md': `---
doc-schema-version: 1
title: "Troubleshooting"
summary: "Observable symptoms, checks, causes, and fixes for ts-pptx."
read_when:
  - Debugging a user-visible failure
  - Adding recovery guidance
  - Explaining known failure signatures
doc_type: "troubleshooting"
---

# Troubleshooting

Start from what the user can observe, then map to checks and fixes.

## Symptom

Describe the visible failure.

Checks:

- Add concrete commands or files to inspect.

Likely causes:

- Add confirmed causes only.

Fix:

- Add the smallest reliable fix or workaround.
`,
}

/** The display name templates are rendered with: the flag, else the literal, else package name. */
function projectName(root, explicit) {
	if (explicit) return explicit
	if (!PROJECT_NAME.includes('{{')) return PROJECT_NAME
	const packageJson = path.join(root, 'package.json')
	if (existsSync(packageJson)) {
		try {
			const name = String(JSON.parse(readFileSync(packageJson, 'utf8')).name ?? '').trim()
			if (name) return name.replace(/^@/, '').split('/').pop()
		} catch {
			/* fall through to the directory name */
		}
	}
	return path.basename(root)
}

function writeFile(root, relativePath, content, force, dryRun) {
	const target = path.join(root, relativePath)
	if (existsSync(target) && !force) return `preserve: ${relativePath}`
	if (dryRun) return `${existsSync(target) ? 'overwrite' : 'create'}: ${relativePath}`
	mkdirSync(path.dirname(target), { recursive: true })
	writeFileSync(target, content, 'utf8')
	return `write: ${relativePath}`
}

function addPackageScripts(root, dryRun) {
	const packageJsonPath = path.join(root, 'package.json')
	if (!existsSync(packageJsonPath)) return null

	const pkg = JSON.parse(readFileSync(packageJsonPath, 'utf8'))
	pkg.scripts ??= {}
	if (typeof pkg.scripts !== 'object' || Array.isArray(pkg.scripts))
		throw new Error('package.json scripts must be an object')

	let changed = false
	for (const [name, command] of Object.entries(PACKAGE_SCRIPTS)) {
		if (pkg.scripts[name] !== command) {
			pkg.scripts[name] = command
			changed = true
		}
	}
	if (!changed) return 'ok: package.json docs scripts already present'
	if (dryRun) return 'update: package.json docs scripts'
	writeFileSync(packageJsonPath, JSON.stringify(pkg, null, 2) + '\n', 'utf8')
	return 'write: package.json docs scripts'
}

const { values } = parseArgs({
	options: {
		'project-name': { type: 'string' },
		force: { type: 'boolean', default: false },
		'dry-run': { type: 'boolean', default: false },
		'no-package-scripts': { type: 'boolean', default: false },
	},
})

const root = process.cwd()
const name = projectName(root, values['project-name'])
for (const [relativePath, template] of Object.entries(TEMPLATES)) {
	console.log(writeFile(root, relativePath, template.replaceAll('ts-pptx', name), values.force, values['dry-run']))
}
if (!values['no-package-scripts']) {
	const result = addPackageScripts(root, values['dry-run'])
	if (result) console.log(result)
}
