#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path


PROJECT_NAME = "PptxGenJS"
PACKAGE_SCRIPTS = {
    "docs:init": "python3 scripts/docs-init.py",
    "docs:list": "python3 scripts/docs-list.py",
    "docs:new": "python3 scripts/docs-new.py",
    "docs:api": "node scripts/docs-api.mjs",
    "docs:llms": "node scripts/generate-llms-docs.mjs",
    "docs:check": "pnpm run docs:api && python3 scripts/docs-check.py",
    "docs:prepare": "pnpm run docs:api && pnpm run docs:llms",
    "docs:dev": "pnpm run docs:prepare && vitepress dev docs",
    "docs:build": "pnpm run docs:prepare && python3 scripts/docs-check.py && vitepress build docs",
    "docs:preview": "vitepress preview docs",
}


def project_name(root: Path, explicit: str | None = None) -> str:
    if explicit:
        return explicit
    if "{{" not in PROJECT_NAME:
        return PROJECT_NAME

    package_json = root / "package.json"
    if package_json.exists():
        try:
            package = json.loads(package_json.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            package = {}
        name = str(package.get("name", "")).strip()
        if name:
            return name.removeprefix("@").split("/")[-1]

    return root.name


def render(template: str, name: str) -> str:
    return template.replace("PptxGenJS", name)


TEMPLATES = {
    ".agents/skills/project-documentation/SKILL.md": """---
name: project-documentation
description: Use when creating, updating, or reviewing README, docs, AGENTS.md, CLI docs, config docs, architecture docs, troubleshooting docs, or behavior-linked documentation in this repository.
---

# Project Documentation

Use this skill for documentation work in this repository.

## Workflow

1. Run `python3 scripts/docs-list.py` when available.
2. Read the docs whose `read_when` hints match the task.
3. Inspect source, tests, package scripts, CLI help, config schemas, and current
   docs before making behavior-sensitive claims.
4. Update docs when architecture, APIs, CLI commands, config, setup, or user
   workflows change.
5. Use `python3 scripts/docs-new.py <slug> --title "..." --summary "..."`
   for new pages.
6. Update `docs/docs.json` when a page should be discoverable in navigation.
7. Run `pnpm run docs:check` before handoff so generated API docs are refreshed
   before scaffold validation.

## Page Rules

Every page under `docs/` needs frontmatter:

```yaml
---
doc-schema-version: 1
title: "Page Title"
summary: "One sentence describing this page."
read_when:
  - When an agent should read this page
doc_type: "guide"
---
```

Allowed `doc_type` values: `overview`, `architecture`, `guide`, `reference`,
`troubleshooting`, `decision`, `runbook`.

## Source-Backed Claims

- CLI docs come from implementation, help output, package scripts, and tests.
- Config docs come from schemas, defaults, parser code, and generated metadata.
- API docs come from exported types, handlers, and tests.
- Architecture docs come from current module boundaries.
- Dependency behavior comes from upstream docs/source/types.

Separate current behavior, planned behavior, and TODOs. Do not invent behavior
to make a page feel complete.

## Generated Site Docs

- `docs/docs.json` is the canonical navigation source for agents and VitePress.
- `docs/reference/api/` is generated by `pnpm run docs:api` from public package
  entry points and should not be hand-edited.
- `docs/public/llms.txt` and `docs/public/llms-full.txt` are generated by
  `pnpm run docs:llms`.
- Run `pnpm run docs:build` to verify the generated TypeDoc reference,
  `llms.txt`, scaffold docs checks, and the VitePress static site together.
""",
    "docs/docs.json": """{
  "name": "PptxGenJS",
  "description": "Documentation for PptxGenJS.",
  "navigation": [
    {
      "group": "Start",
      "pages": ["index", "architecture"]
    },
    {
      "group": "Reference",
      "pages": ["reference/index", "troubleshooting"]
    }
  ]
}
""",
    "docs/index.md": """---
doc-schema-version: 1
title: "PptxGenJS"
summary: "Start here for the purpose, setup, and main workflows in PptxGenJS."
read_when:
  - Getting oriented in this project
  - Updating the main project overview
doc_type: "overview"
---

# PptxGenJS

This page is the documentation entry point for PptxGenJS.

## What This Project Does

Describe the job this project performs, who uses it, and what it intentionally
does not own.

## Quickstart

Add the shortest reliable path from a fresh checkout to a working result.

## Main Workflows

Link to setup, architecture, reference, and troubleshooting pages as they become
useful.

## Verification

Record the smallest command that proves the current project still works.
""",
    "docs/architecture.md": """---
doc-schema-version: 1
title: "Architecture"
summary: "How PptxGenJS is structured and where major responsibilities live."
read_when:
  - Changing module boundaries
  - Explaining architecture or ownership decisions
  - Reviewing whether a new feature belongs in the current structure
doc_type: "architecture"
---

# Architecture

Use this page to keep the project's structure legible as features evolve.

## Responsibilities

Describe the main modules, packages, services, or scripts and what each owns.

## Boundaries

Call out decisions that should not be rediscovered during routine feature work.

## Data And Control Flow

Describe important runtime flows when they become stable enough to document.

## Extension Points

List supported ways to add behavior without rewriting core code.
""",
    "docs/reference/index.md": """---
doc-schema-version: 1
title: "Reference"
summary: "Stable commands, configuration, APIs, and generated references for PptxGenJS."
read_when:
  - Looking up command, config, or API details
  - Adding a reference page
  - Verifying docs against exported contracts
doc_type: "reference"
---

# Reference

Keep exhaustive contracts here instead of burying them in guides.

## Commands

Document stable commands, flags, inputs, outputs, and exit codes.

## Configuration

Document supported config fields, defaults, precedence, and migration notes.

## APIs

Document stable public APIs, request/response shapes, errors, and lifecycle
states.
""",
    "docs/troubleshooting.md": """---
doc-schema-version: 1
title: "Troubleshooting"
summary: "Observable symptoms, checks, causes, and fixes for PptxGenJS."
read_when:
  - Debugging a user-visible failure
  - Adding recovery guidance
  - Explaining known failure signatures
doc_type: "troubleshooting"
---

# Troubleshooting

Start from what the user can observe, then map to checks and fixes.

## Symptom

Describe the visible failure.

Checks:

- Add concrete commands or files to inspect.

Likely causes:

- Add confirmed causes only.

Fix:

- Add the smallest reliable fix or workaround.
""",
}


def write_file(root: Path, relative_path: str, content: str, force: bool, dry_run: bool) -> str:
    target = root / relative_path
    if target.exists() and not force:
        return f"preserve: {relative_path}"
    if dry_run:
        action = "overwrite" if target.exists() else "create"
        return f"{action}: {relative_path}"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    return f"write: {relative_path}"


def add_package_scripts(root: Path, dry_run: bool) -> str | None:
    package_json = root / "package.json"
    if not package_json.exists():
        return None

    package = json.loads(package_json.read_text(encoding="utf-8"))
    scripts = package.setdefault("scripts", {})
    if not isinstance(scripts, dict):
        raise ValueError("package.json scripts must be an object")

    changed = False
    for name, command in PACKAGE_SCRIPTS.items():
        if scripts.get(name) != command:
            scripts[name] = command
            changed = True

    if not changed:
        return "ok: package.json docs scripts already present"
    if dry_run:
        return "update: package.json docs scripts"
    package_json.write_text(json.dumps(package, indent=2) + "\n", encoding="utf-8")
    return "write: package.json docs scripts"


def main() -> int:
    parser = argparse.ArgumentParser(description="Initialize small-project documentation files.")
    parser.add_argument("--project-name", help="Display name for generated docs.")
    parser.add_argument("--force", action="store_true", help="Overwrite existing scaffold files.")
    parser.add_argument("--dry-run", action="store_true", help="Print intended changes without writing.")
    parser.add_argument(
        "--no-package-scripts",
        action="store_true",
        help="Do not add docs scripts to package.json when present.",
    )
    args = parser.parse_args()

    root = Path.cwd()
    name = project_name(root, args.project_name)
    for relative_path, template in TEMPLATES.items():
        print(write_file(root, relative_path, render(template, name), args.force, args.dry_run))

    if not args.no_package_scripts:
        result = add_package_scripts(root, args.dry_run)
        if result:
            print(result)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
