#!/usr/bin/env node
// Validate the docs tree: frontmatter schema, balanced code fences, navigation entries that
// resolve to a real page, and internal links that resolve to a real route or file.
//
// Runs in `docs:check` and again inside `docs:build`, so a broken link fails the docs build
// rather than shipping a 404. `docs:build` is in turn part of `verify` and `check:static`, so
// the failure lands on the change that caused it rather than on the Pages deploy.
//
// With `--dist`, checks the built output instead: every URL in the generated llms.txt files
// must name a page VitePress actually emitted. That is a separate pass because it can only run
// *after* `vitepress build`, and the source checks above only need the markdown tree.

import { existsSync, readdirSync, readFileSync } from 'node:fs'
import path from 'node:path'

import { ALLOWED_DOC_TYPES, compactStrings, parseFrontmatter, requireDocsDir, walkDocs } from './docs-frontmatter.mjs'
import { ROOT, isMain, parseCliOrExit, runCli } from './script-utils.mjs'

const REQUIRED_FIELDS = ['doc-schema-version', 'doc_type', 'read_when', 'summary', 'title']

/**
 * Pages deliberately absent from `docs.json` navigation, each for a reason that is not
 * "nobody got round to it". Listing one *in* the nav is a failure too, so an entry that
 * stops being true reports rather than quietly granting slack.
 *
 * `doc-index` is generated by `scripts/docs-index.mjs` and gitignored — it is the flat
 * index the llms.txt build reads, not a page a reader navigates to.
 */
const NAV_EXEMPT = new Set(['doc-index'])

/**
 * Generated page *trees*, exempt from the navigation check by prefix rather than by name.
 *
 * TypeDoc emits a few hundred pages under `docs/reference/api/`, and the sidebar links the
 * one entry point (`reference/api/index`) rather than every symbol — so these are exempt
 * from the orphan direction but must stay eligible for the nav direction, which is why they
 * are not in `NAV_EXEMPT` above.
 *
 * The prefix form is also what keeps the verdict a property of the repo rather than of the
 * machine, the same concern `scripts/path-refs.mjs` documents at length: this tree is
 * gitignored, so it is absent in a fresh checkout and present in any working copy that has
 * run `docs:api`. Skipped by prefix, both states agree.
 */
const GENERATED_TREES = ['reference/api/']
// Markdown inline links, excluding images (`!` prefix) and tolerating a trailing "title".
const MARKDOWN_LINK_RE = /(?<!!)\[[^\]]+\]\(([^)\s]+)(?:\s+"[^"]*")?\)/g

/**
 * Normalize a site route: strip query/hash and surrounding slashes, keeping a leading `/`.
 * @param {string} route
 * @returns {string}
 */
function normalizeRoute(route) {
	const bare = (route.split('#', 1)[0]?.split('?', 1)[0] ?? '').replace(/^\/+|\/+$/g, '')
	return bare ? `/${bare}` : '/'
}

/**
 * Every route a docs page is reachable at (a page, plus `/` for index pages).
 * @param {string} relativePath
 * @returns {Set<string>}
 */
function routesFor(relativePath) {
	const stem = relativePath.replace(/\.md$/, '')
	const routes = new Set([normalizeRoute(stem)])
	if (stem === 'index') routes.add('/')
	if (stem.endsWith('/index')) routes.add(normalizeRoute(stem.slice(0, -'/index'.length)))
	return routes
}

/**
 * Every `pages:` entry anywhere in a docs.json navigation tree.
 * @param {unknown} value
 * @returns {string[]}
 */
function collectNavPages(value) {
	/** @type {string[]} */
	const pages = []
	if (Array.isArray(value)) {
		for (const item of value) pages.push(...collectNavPages(item))
	} else if (value && typeof value === 'object') {
		for (const [key, item] of Object.entries(value)) {
			if (key === 'pages' && Array.isArray(item)) {
				for (const page of item) {
					if (typeof page === 'string') pages.push(page)
					else pages.push(...collectNavPages(page))
				}
			} else {
				pages.push(...collectNavPages(item))
			}
		}
	}
	return pages
}

/**
 * A link target that leaves the docs site entirely.
 * @param {string} target
 * @returns {boolean}
 */
function isExternal(target) {
	return /^[a-z][a-z0-9+.-]*:/i.test(target) || target.startsWith('//')
}

/**
 * Is `target` inside `root`? Not a prefix test: `startsWith` would also accept a `docs-extra/`
 * sibling, which is outside the tree but shares the leading characters.
 * @param {string} root
 * @param {string} target
 * @returns {boolean}
 */
function isInside(root, target) {
	const rel = path.relative(root, target)
	return rel !== '' && !rel.startsWith('..') && !path.isAbsolute(rel)
}

/**
 * @param {string} docsDir
 * @param {string} rel docs-relative page path
 * @returns {string[]} one message per problem found
 */
function checkFrontmatter(docsDir, rel) {
	const { data, error } = parseFrontmatter(path.join(docsDir, rel))
	if (error) return [`${rel}: ${error}`]

	const errors = []
	for (const field of REQUIRED_FIELDS) {
		if (!Object.hasOwn(data, field)) errors.push(`${rel}: missing frontmatter field \`${field}\``)
	}
	if (String(data['doc-schema-version'] ?? '').trim() !== '1') errors.push(`${rel}: \`doc-schema-version\` must be 1`)
	for (const field of ['title', 'summary', 'doc_type']) {
		if (!String(data[field] ?? '').trim()) errors.push(`${rel}: \`${field}\` must be non-empty`)
	}
	const docType = String(data.doc_type ?? '').trim()
	if (docType && !ALLOWED_DOC_TYPES.includes(docType)) {
		errors.push(`${rel}: \`doc_type\` must be one of: ${ALLOWED_DOC_TYPES.join(', ')}`)
	}
	if (compactStrings(data.read_when).length === 0) errors.push(`${rel}: \`read_when\` must contain at least one hint`)
	return errors
}

/**
 * @param {string} docsDir
 * @param {string} rel docs-relative page path
 * @returns {string[]}
 */
function checkCodeFences(docsDir, rel) {
	const text = readFileSync(path.join(docsDir, rel), 'utf8')
	const fences = text.split(/\r?\n/).filter((line) => line.trimStart().startsWith('```')).length
	return fences % 2 ? [`${rel}: unbalanced fenced code block`] : []
}

/**
 * @param {string} docsDir
 * @param {string[]} relPaths every docs-relative page path
 * @returns {string[]}
 */
function checkDocsJson(docsDir, relPaths) {
	const configPath = path.join(docsDir, 'docs.json')
	if (!existsSync(configPath)) return ['docs/docs.json: missing docs navigation file']

	let config
	try {
		config = JSON.parse(readFileSync(configPath, 'utf8'))
	} catch (error) {
		return [`docs/docs.json: invalid JSON: ${error instanceof Error ? error.message : String(error)}`]
	}

	const pageKeys = new Set(relPaths.map(/** @param {string} rel */ (rel) => rel.replace(/\.md$/, '')))
	/** @type {string[]} */
	const errors = []
	/** @type {Set<string>} */
	const navKeys = new Set()
	for (const page of collectNavPages(config.navigation ?? [])) {
		const key = page.trim().replace(/^\/+|\/+$/g, '')
		navKeys.add(key)
		if (!pageKeys.has(key)) errors.push(`docs/docs.json: navigation page \`${page}\` has no matching docs page`)
	}

	// And the other direction. Checking nav -> page alone only catches a page that was
	// deleted or renamed; it says nothing about one that was *added* and never listed,
	// which is the failure that actually happened — `errors.md`, `diagnostics.md` and
	// `animations-and-transitions.md` sat outside the sidebar with `docs:build` green,
	// reachable only from other pages' links and from search. A page nothing navigates to
	// is not a dead page, so this is a nav omission rather than a content problem, but it
	// is exactly as invisible either way.
	for (const key of pageKeys) {
		if (navKeys.has(key) || NAV_EXEMPT.has(key)) continue
		if (GENERATED_TREES.some((prefix) => key.startsWith(prefix))) continue
		errors.push(`docs/docs.json: docs page \`${key}.md\` is in no navigation group`)
	}

	for (const key of NAV_EXEMPT) {
		if (navKeys.has(key)) errors.push(`docs/docs.json: \`${key}\` is exempt from navigation but is listed in it`)
	}
	return errors
}

/**
 * Every link problem on one page. Exported for the test, per the gate-script convention in
 * `script-utils.mjs`: the rules below are judgement calls about what VitePress will resolve.
 * @param {string} docsDir the docs tree root
 * @param {string} rel the page, relative to `docsDir`
 * @param {Set<string>} routes every route the site serves
 * @returns {string[]}
 */
export function checkLinks(docsDir, rel, routes) {
	const filePath = path.join(docsDir, rel)
	const text = readFileSync(filePath, 'utf8')
	const errors = []
	const docsRoot = path.resolve(docsDir)

	for (const match of text.matchAll(MARKDOWN_LINK_RE)) {
		const target = (match[1] ?? '').trim()
		if (!target || target.startsWith('#') || isExternal(target)) continue

		const targetPath = target.split('#', 1)[0]?.split('?', 1)[0] ?? ''
		if (targetPath.startsWith('/')) {
			if (!routes.has(normalizeRoute(targetPath))) errors.push(`${rel}: broken docs route \`${target}\``)
			continue
		}
		// Only `.md` targets are routes. Anything else (an image, a `.txt` under public/) is an
		// asset VitePress passes through, and is not this gate's business wherever it resolves.
		if (!targetPath.endsWith('.md')) continue

		const resolved = path.resolve(path.dirname(filePath), targetPath)
		// A relative `.md` link that escapes docs/ is the failure that stalled the Pages deploy for
		// three days: the file exists on disk, so it looks fine locally, but it is not a page in the
		// site and VitePress fails the build on the dead link. Skipping these as "not ours to check"
		// is what let it reach the Docs workflow. Repo files outside docs/ get an absolute blob URL.
		if (!isInside(docsRoot, resolved)) {
			errors.push(
				`${rel}: relative link \`${target}\` points outside docs/; VitePress has no route for it — use the absolute URL`
			)
		} else if (!existsSync(resolved)) {
			errors.push(`${rel}: broken relative link \`${target}\``)
		}
	}
	return errors
}

/**
 * The URL prefix the published site actually answers on, derived rather than restated: the
 * GitHub Pages host comes from `repository`, the path from the VitePress `base`. Writing the
 * value out a second time is what let `llms.txt` drift to a host that never existed.
 * @param {string} docsDir
 * @returns {{base: string | null, errors: string[]}}
 */
function canonicalBase(docsDir) {
	if (process.env.DOCS_BASE_URL) return { base: process.env.DOCS_BASE_URL.replace(/\/?$/, '/'), errors: [] }

	const pkg = JSON.parse(readFileSync(path.join(docsDir, '..', 'package.json'), 'utf8'))
	const slug = String(pkg.repository?.url ?? pkg.homepage ?? '').match(/github\.com\/([^/]+)\/([^/.#]+)/)
	if (!slug) return { base: null, errors: ['package.json: cannot derive the GitHub Pages host from `repository`'] }

	const config = readFileSync(path.join(docsDir, '.vitepress', 'config.mts'), 'utf8')
	const configured = config.match(/^\s*base:.*?'([^']+)'/m)
	if (!configured) return { base: null, errors: ['docs/.vitepress/config.mts: cannot read the `base` option'] }

	// An unreadable `base` collapses to `/`, which the slug check below then rejects loudly.
	const base = (process.env.VITEPRESS_BASE ?? configured[1] ?? '').replace(/\/?$/, '/')
	const errors = []
	// A project Pages site is served under /<repo>/, so a `base` that disagrees means the whole
	// site 404s no matter how well-formed the routes underneath it are.
	if (!process.env.VITEPRESS_BASE && base !== `/${slug[2]}/`) {
		errors.push(`docs/.vitepress/config.mts: \`base\` is \`${base}\`, but Pages serves this repo at \`/${slug[2]}/\``)
	}
	return { base: `https://${slug[1]}.github.io${base}`, errors }
}

// How each generated file writes the URLs it advertises. These have to stay per-file rather than
// being tried against both: llms-full.txt embeds whole page bodies, so a link pattern applied to
// it would also match the ordinary markdown links *inside* those bodies.
const ADVERTISED_URL_RE = {
	'llms-full.txt': /^URL: (\S+)$/gm,
	'llms.txt': /^- \[[^\]]+\]\((\S+?)\)/gm,
}

/**
 * The URLs a generated llms file advertises.
 * @param {string} text
 * @param {RegExp} pattern
 * @returns {Set<string>}
 */
function advertisedUrls(text, pattern) {
	const urls = [...text.matchAll(pattern)].map((match) => match[1] ?? '')
	return new Set(urls.map((url) => url.split('#', 1)[0]?.split('?', 1)[0] ?? ''))
}

/**
 * Every advertised URL must map to a file in the build. VitePress runs with `cleanUrls`, so a
 * leaf page is `x.html` and only a directory index is `x/index.html` — the mapping below is the
 * one the server applies, so a route the generator invents cannot pass by looking plausible.
 * @param {string} docsDir
 * @returns {string[]}
 */
function checkGeneratedUrls(docsDir) {
	const dist = path.join(docsDir, '.vitepress', 'dist')
	if (!existsSync(dist)) return ['docs/.vitepress/dist: missing; run `vitepress build docs` before `--dist`']

	const { base, errors } = canonicalBase(docsDir)
	if (!base) return errors

	for (const [name, pattern] of Object.entries(ADVERTISED_URL_RE)) {
		const file = path.join(dist, name)
		if (!existsSync(file)) {
			errors.push(`${name}: not present in the build output`)
			continue
		}
		const urls = advertisedUrls(readFileSync(file, 'utf8'), pattern)
		if (urls.size === 0) {
			errors.push(`${name}: advertises no URLs, so nothing was verified`)
			continue
		}
		for (const url of [...urls].sort()) {
			if (!url.startsWith(base)) {
				errors.push(`${name}: \`${url}\` is not under the published base \`${base}\``)
				continue
			}
			const rest = url.slice(base.length)
			const page = rest === '' ? 'index.html' : rest.endsWith('/') ? `${rest}index.html` : `${rest}.html`
			if (!existsSync(path.join(dist, page))) errors.push(`${name}: \`${url}\` has no page in the build (${page})`)
		}
	}
	return errors
}

const USAGE = `Validate the docs tree: frontmatter, code fences, nav entries and internal links.

  pnpm run docs:check
  node scripts/docs-check.mjs --dist    # check the built output instead

Options:
  --dist       check that every URL in the generated llms.txt files names a built page
  -h, --help   show this message`

/**
 * Every `scripts/*.mjs` must have a row in `scripts/README.md`'s table.
 *
 * That table's own premise is that "the single most useful fact about a script here is not what
 * it does but whether anything runs it", which is worth nothing if a script can be added without
 * anyone answering the question. Four were missing when this was written, two of them
 * (`path-refs.mjs`, `run-steps.mjs`) in every aggregate the repo has.
 *
 * `path-refs.mjs` does not catch this: it checks that cited paths resolve, not that every file
 * is cited. The test is deliberately just "the basename appears in a backticked cell" -- what
 * the row *says* is a human's job; that there is one is not.
 * @returns {string[]} one error per script with no row
 */
function checkScriptsTable() {
	const dir = path.join(ROOT, 'scripts')
	const readme = path.join(dir, 'README.md')
	if (!existsSync(readme)) return ['scripts/README.md: missing']
	const text = readFileSync(readme, 'utf8')
	const documented = new Set([...text.matchAll(/\|\s*`([^`]+)`\s*\|/g)].map((m) => m[1]))
	return readdirSync(dir)
		.filter((name) => name.endsWith('.mjs'))
		.filter((name) => !documented.has(name))
		.map((name) => `scripts/README.md: no table row for \`${name}\` — say what it does and what runs it`)
}

/** @param {string[]} argv */
function main(argv) {
	const { values } = parseCliOrExit(argv, { usage: USAGE, options: { dist: { type: 'boolean', default: false } } })
	const docsDir = requireDocsDir('docs:check')

	if (values.dist) {
		const errors = checkGeneratedUrls(docsDir)
		if (errors.length > 0) {
			for (const error of errors) console.error(`docs:check: ${error}`)
			return 1
		}
		console.log('docs:check: ok (generated llms URLs all resolve to a built page)')
		return 0
	}

	const relPaths = walkDocs(docsDir)

	const routes = new Set()
	for (const rel of relPaths) for (const route of routesFor(rel)) routes.add(route)

	const errors = [...checkDocsJson(docsDir, relPaths), ...checkScriptsTable()]
	for (const rel of relPaths) {
		errors.push(
			...checkFrontmatter(docsDir, rel),
			...checkCodeFences(docsDir, rel),
			...checkLinks(docsDir, rel, routes)
		)
	}

	if (errors.length > 0) {
		for (const error of errors) console.error(`docs:check: ${error}`)
		return 1
	}
	console.log(`docs:check: ok (${relPaths.length} docs page(s))`)
	return 0
}

if (isMain(import.meta.url)) await runCli(() => main(process.argv.slice(2)))
