export { default, Presentation, PptxGenJS } from './browser.js'
export * from './core-enums.js'
export * from './units.js'
export type * from './core-interfaces.js'
export type { PresSlide as Slide } from './core-interfaces.js'
